on:
  repository_dispatch:

  # workflow_dispatch:
    # inputs:
    #   youtubeUrl:
    #     description: "Youtube Url"
    #     required: true
    #   from:
    #     description: "From"
    #     required: true
    #     default: "00:00:00.00"
    #   to:
    #     description: "To"
    #     required: true
    #     default: "00:00:03.00"
    #   text:
    #     description: "Text"
    #     required: true
    #     default: " "
    #   chatId:
    #     description: "Telegram chat id"
    #     required: true
    #     default: ${{ secrets.TELEGRAM_CHAT_ID }}
name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: npm run server -- --youtubeUrl='${{github.event.client_payload.youtubeUrl}}' --from=${{github.event.client_payload.from}} --to=${{github.event.client_payload.to}} --text='${{github.event.client_payload.text}}' --chatId=${{github.event.client_payload.chatId}}
