on:
  repository_dispatch:

name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_API_URL: ${{ secrets.TELEGRAM_API_URL }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: npm run server -- --youtubeUrl='${{github.event.client_payload.youtubeUrl}}' --from=${{github.event.client_payload.from}} --to=${{github.event.client_payload.to}} --text='${{github.event.client_payload.text}}' --chatId=${{github.event.client_payload.chatId}}
