on:
  workflow_dispatch:
    inputs:
      youtubeUrl:
        description: "Youtube Url"
        required: true
      from:
        description: "From"
        required: true
        default: "00:00:00.00"
      to:
        description: "To"
        required: true
        default: "00:00:03.00"
      text:
        description: "Text"
        required: true
      cta:
        description: 'CTA'
        required: true
        default: 'como-ganhar-dinheiro-na-internet.mp4'

name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_API_URL: ${{ secrets.TELEGRAM_API_URL }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: npm run server -- --youtubeUrl='${{github.event.inputs.youtubeUrl}}' --from=${{github.event.inputs.from}} --to=${{github.event.inputs.to}} --text='${{github.event.inputs.text}}' --chatId=${{github.event.inputs.chatId}} --cta=${{github.event.inputs.cta}}
